### PR TITLE
Work around fake timers with zero duration not firing

### PR DESCRIPTION
**Pull request by impl**

### CODE REVIEW

**Review by rick-a-lane-ii — APPROVED** [review]

**Review by hunner — APPROVED** [review]
Zero time firing makes sense for a timer. `NewTicker(0)` actually panics: `panic: non-positive interval for NewTicker`. I guess that would happen here anyway?

**Comment by impl** [comment]
Are you looking at the standard library implementation? The apimachinery implementation (https://pkg.go.dev/k8s.io/apimachinery/pkg/util/clock) doesn't do either of those things, I don't think.

**Comment by hunner** [comment]
Yeah that was for the normal `time` package https://golang.org/pkg/time/

**Comment by impl** [comment]
Yeah, using the real clock time doesn't have this problem because the small amount of time needed for a 0-duration timer to elapse in the real world happens almost instantaneously. The real timer code uses the current time + the duration to construct the time when the timer should fire. So probably you're seeing 1ns from just moving the stack frame into that function.

**Pull request merged**
